let BLB = {
    'Banishing Light':	'C+',
    'Beza, the Bounding Spring':	'A',
    'Brave-Kin Duo':	'C',
    'Brightblade Stoat':	'B',
    "Builder's Talent":	'C',
    "Caretaker's Talent":	'B-',
    'Carrot Cake':	'C+',
    'Crumb and Get It':	'C',
    "Dawn's Truce":	'C',
    'Dewdrop Cure':	'C',
    'Driftgloom Coyote':	'B-',
    'Essence Channeler':	'B',
    'Feather of Flight':	'C',
    'Flowerfoot Swordmaster':	'B',
    'Harvestrite Host':	'B-',
    'Hop to It':	'B',
    'Intrepid Rabbit':	'B-',
    'Jackdaw Savior':	'B',
    'Jolly Gerbils':	'B-',
    'Lifecreed Duo':	'C',
    "Mabel's Mettle":	'C+',
    'Mouse Trapper':	'C',
    'Nettle Guard':	'C',
    'Parting Gust':	'C',
    'Pileated Provisioner':	'C',
    'Rabbit Response':	'C',
    'Repel Calamity':	'B-',
    'Salvation Swan':	'A-',
    'Season of the Burrow':	'A-',
    'Seasoned Warrenguard':	'C',
    'Shrike Force':	'B-',
    'Sonar Strike':	'C+',
    'Star Charter':	'B',
    'Starfall Invocation':	'A+',
    'Thistledown Players':	'C',
    'Valley Questcaller':	'B+',
    'Warren Elder':	'C+',
    'Warren Warleader':	'A',
    'Wax-Wane Witness':	'C',
    'Whiskervale Forerunner':	'B+',
}