export function DSK() {

    const Duskmourn = {
    "Meathook Massacre II": "C-",
    "Valgavoth's Onslaught": "A",
    "Valgavoth's Lair": "B-",
    "Rip, Spawn Hunter": "C+",
    "Reluctant Role Model": "B",
    "Niko, Light of Hope": "A+",
    'Chainsaw': 'B',
    'Fear of Missing Out': 'B',
    'Razorkin Needlehead': 'C',
    'The Rollercrusher Ride': 'A',
    'Screaming Nemesis': 'A-',
    'Cursed Recording': 'D+',
    'Enduring Courage': 'A-',
    "Nashi, Searcher in the Dark": 'B',
    'Leyline of Mutation': 'F',
    'Leyline of Resonance': 'F',
    'Leyline of the Void': 'F',
    'Leyline of Transformation': 'F',
    'Waltz of Rage': 'A-',
    'Overlord of the Boilerbilges': 'A',
    
    'Silent Hallcreeper': 'A-',
    'Abhorrent Oculus': 'B+',
    'Entity Tracker': 'A-',
    'The Mindskinner': 'F',
    "The Tale of Tamiyo": 'D',
    'Enduring Curiosity': 'B+',
    'Lay Line of Transformation': 'F',
    'Overlord of the Floodpits': 'A-',
    'Marina Vendrell': 'D-',
    "Marina Vendrell's Grimoire": 'D-',
    'Central Elevator': 'D+',
    'Mirror Room // Fractured Realm': 'C+',
    'Demonic Counsel': 'D',
    'Come Back Wrong': 'B-',
    'Unstoppable Slasher': 'A',
    'Enduring Tenacity': 'D',
    "Funeral Room // Awakening Hall": 'A',
    "Patchwork Beastie": 'B',
    'Grievous Wound': 'F',
    'Overlord of the Balemurk': 'A-',
    "Overlord of the Hauntwoods": 'A',
    'Doomsday Excruciator': 'C-',
    'Unholy Annex': 'B+',
    'Valgavoth, Terror Eater': 'B-',
    'Dazzling Theater // Prop Room': 'D',
    'Ghost Vacuum': 'C',
    'Marvin, Murderous Mimic': 'D+',
    'Dissection Tools': 'A-',
    'Blazemire Verge': 'B',
    'Peer Past the Veil': 'D-',
    "Roaring Furnace // Steaming Sauna": "B+",
    'Role Model': 'B-',
    'Enduring Innocence': 'B+',
    'Split Up': 'B-',
    'Toby, Beastie Befriender': 'B+',
    'Unidentified Hovership': 'A-',
    'Leyline of Hope': 'F',
    'Ghostly Dancers': 'A+',
    "Restriced Office // Lecture Hall": "C",
    'The Wandering Rescuer': 'A+',
    'Dazzling Theater': 'F',
    'Overlord of the Mistmoors': 'A+',
    "Dollmaker's Shop // Porcelain Gallery": 'A',
    'Razerkin Needlehead': 'C+',
    'Layline of the Rage': 'F',
    'Vault of Rage': 'B+',
    "The Jolly Balloon Man": "B",
    "The Swarmweaver": "A",
     
    'Charred Foyer // Warped Space': 'C+',
    
    'Twitching Doll': 'A-',
    'Enduring Vitality': 'B',
    'Hawood Shrier': 'B',
    'Omnivorous Flytrap': 'B-',
    'Tyvar, the Pummeler': 'A',
    'Hedge Shredder': 'A-',
    'Kona, Rescue Beastie': 'D+',
    'Wrong Mutation': 'F',
    'Balustrade Wurm': 'A',
    'Overlord of the Haunt Woods': 'B+',
    'Walk-In Closet // Forgotten Cellar': 'D',
    'Soul Warden': 'C',
    'Hallowed Haunting': 'D',
    'Phantasmal Image': 'C+',
    'Expropriate': 'D',
    'Cabal Ritual': 'F',
    'Damnation': 'B+',
    "Unholy Annex // Ritual Chamber": "B+",
    'Unholy Heat': 'A-',
    'Maddening Hex': 'F',
    "Naru's Revival": 'F',
    'Collected Company': 'D',
    "Hauntwoods Shrieker": 'B',
    "Kaito, Bane of Nightmares": "A-",
    "Undead Sprinter": "B",
    "Victor, Valgavoth's Seneschal": "C+",
    "Zimone, All-Questioning": "A",
    "Winter, Misanthropic Guide": "F",

    // Gold Uncommons
    "Gremlin Tamer": "B-",
    "Inquisitive Glimmer": "B",
    "Fear of Infinity": "C+",
    "Skullsnap Nuisance": "B-",
    "Disturbing Mirth": "B (Synergy B)",
    "Sawblade Skinripper": "C+",
    "Beastie Beatdown": "B",
    "Wildfire Wickerfolk": "B",
    "Baseball Bat": "C",
    "Shrewd Storyteller": "C",
    "Rite of the Moth": "C+",
    "Shroudstomper": "C+",
    "Intruding Soulrager": "C-",
    "Smokey Lounge // Misty Salon": "Build-around C+",
    "Broodspinner": "B+",
    "Drag to the Roots": "C+",
    "Arabella, Abandoned Doll": "B+",
    "Midnight Mayhem": "B",
    "Growing Dread": "B",
    "Oblivious Bookworm": "A-",

    // uncommon artifacts
    "Bear Trap": "D+",
    "Found Footage": "D+",
    "Friendly Teddy": "D+",
    "Glimmerlight": "C",
    "Malevolent Chandelier": "D",
    "Keys to the House": "C",
    "Saw": "D",
    "Attack-in-the-Box": "C-",
    "Haunted Screen": "C",
    "Conductive Machete": "C+",
    
    "Terramorphic Expanse": "B",

    //White commons
    "Jump Scare": "C+",
    "Possessed Goat": "D+",
    "Acrobatic Cheerleader": "C",
    "Surveillance": "C+",
    "Cult Healer": "C-",
    "Hardened Escort": "C",
    "Living Phone": "D",
    "Trapped in the Screen": "B-",
    "Friendly Ghost": "C+",
    "Unsettling Twins": "B",
    "Emerge from the Cocoon": "C+",
    "Fear of Immobility": "C",
    "Grand Entryway // Elegant Rotunda": "C+",
    "Seized from Slumber": "C",
    "In Spirit": "C",
    "Shepherding Spirits": "C",
    "Ethereal Armor": "B-",
    "Optimistic Scavenger": "B+",
    "Shardmage's Rescue": "B",
    "Unwanted Remake": "F",
    "Veteran Survivor": "C+",
    "Exorcise": "C+",
    "Orphans of the Wheat": "C+",
    "Sheltered by Ghosts": "B-",
    "Splitskin Doll": "B",
    "Glimmer Seeker": "C+",
    "Patched Plaything": "B-",
    "Savior of the Small": "C-",
    "Lionheart Glimmer": "C",
    "Fear of Abduction": "C+",
    "Surgical Suite // Hospital Room": "B",
    "Fear of Surveillance": "C",

    //Blue Commons
    "Enter the Enigma": "C",
    "Unable to Scream": "C-",
    "Creeping Peeper": "D+",
    "Don't Make a Sound": "C-",
    "Piranha Fly": "D+",
    "Stalked Researcher": "C-",
    "Erratic Apparition": "D",
    "Tunnel Surveyor": "C+",
    "Twist Reality": "C+",
    "Clammy Prowler": "D+",
    "Glimmerburst": "B-",
    "Vanish from Sight": "C+",
    "Underwater Tunnel // Slimy Aquarium": "C+",
    "Daggermaw Megalodon": "C+",
    "Meat Locker // Drowned Diner": "C",
    "Scrabbling Skullcrab": "D",
    "Fear of Isolation": "C+",
    "Floodpits Drowner": "B",
    "Get Out": "C+",
    "Paranormal Analyst": "B",
    "Stay Hidden, Stay Silent": "C+",
    "Cursed Windbreaker": "B-",
    "Fear of Impostors": "C+",
    "Unnerving Grasp": "B+",
    "Unwilling Vessel": "C-",
    "Ghostly Keybearer": "D+",
    "Fear of Failed Tests": "C-",
    "Fear of Falling": "C",
    "Bottomless Pool // Locker Room": "B-",
    "Duskmourn's Domination": "D+",

    //Black commons
    "Fear of Lost Teeth": "C+",
    "Final Vengeance": "C",
    "Balemurk Leech": "D+",
    "Give In to Violence": "C-",
    "Innocuous Rat": "C+",
    "Winter's Intervention": "C+",
    "Appendage Amalgam": "C-",
    "Cracked Skull": "C",
    "Murder": "C+",
    "Resurrected Cultist": "C+",
    "Cackling Slasher": "D",
    "Fanatic of the Harrowing": "C+/C-",
    "Fear of the Dark": "D",
    "Spectral Snatcher": "C-",
    "Derelict Attic // Widow's Walk": "D+",
    "Valgavoth's Faithful": "C",
    "Cynical Loner": "C",
    "Nowhere to Run": "B-",
    "Osseous sticktwister": "B",
    "Sporogenic Infection": "B-",
    "Commune with Evil": "C",
    "Killer's Mask": "C",
    "Popular Egotist": "B-",
    "Withering Torment": "C+",
    "Dashing Bloodsucker": "C",
    "Let's Play a Game": "Synergy C",
    "Defiled Crypt // Cadaver Lab": "C",
    "Live or Die": "B-",
    "Miasma Demon": "C-",
    "Vile Mutilator": "C-",

    // Red commons/uncommons
    "clockwork Percussionist": "C+",
    "Turn Inside Out": "C+",
    "Grab the Prize": "D+",
    "Hand that Feeds": "C-",
    "Ragged Playmate": "C",
    "Scorching Dragonfire": "B",
    "Rampaging Soulrager": "D+",
    "Vicious Clown": "D+",
    "Most Valuable Slayer": "B-",
    "Ripchain Razorkin": "C",
    "Boilerbilges Ripper": "D",
    "Impossible Inferno": "C+",
    "Bedhead Beastie": "D+",
    "Glassworks // Shattered Yard": "C+",
    "Ticket Booth // Tunnel of Hate": "C+",
    "Norin, Swift Survivalist": "C+",
    "Trial of Agony": "C+",
    "Violent Urge": "B-",
    "Betrayer's Bargain": "B-",
    "Irreverent Gremlin": "B",
    "Piggy Bank": "B",
    "Pyroclasm": "C+",
    "Untimely Malfunction": "F",
    "Fear of Being Hunted": "C+",
    "Vengeful Possession": "C+",
    "Diversion Specialist": "C",
    "Infernal Phantom": "C",
    "Painter's Studio // Defaced Gallery": "B-",
    "Razorkin Hordecaller": "B",
    "Fear of Burning Alive": "B-",

    //Green Commons/uncommons
    "Flesh Burrower": "C",
    "Horrid Vigor": "D+",
    "Manifest Dread": "B",
    "Monstrous Emergence": "C+",
    "Say Its Name": "C+",
    "Pathcwork Beastie": "B+",
    "Altanak, the Thrice-Called": "B-",
    "Wary Watchdog": "C+",
    "Cryptid Inspector": "C",
    "Frantic Strength": "C-",
    "Grasping Longneck": "C",
    "Spineseeker Centipede": "C+",
    "Anthropede": "D+",
    "Cautious Survivor": "D+",
    "Bashful Beastie": "C+",
    "Slavering Branchsnapper": "C+",
    "Moldering Gym // Weight Room": "C+",
    "Coordinated Clobbering": "C+",
    "Insidious Fungus": "B-",
    "Patrick Beast": "B-",
    "Cathartic Parting": "D+",
    "House Cartographer": "C+",
    "Overgrown Zealot": "C+",
    "Break Down the Door": "C+",
    "Defiant Survivor": "C+",
    "Fear of Exposure": "C",
    "Under the Skin": "B+",
    "Threats Around Every Corner": "B-",
    "Wickerfolk Thresher": "B-",
    "Rootwise Survivor": "D+",
    "Greenhouse // Rickety Gazebo": "D+",

    //Lands
    "Bleeding Woods": "C+",
    "Etched Cornfield": "C+",
    "Floodfarm Verge": "C+",
    "Gloomlake Verge": "C+",
    "Hushwood Verge": "C+",
    "Island": "F",
    "Lakeside Shack": "C+",
    "Mountain": "F",
    "Murky Sewer": "C+",
    "Neglected Manor": "C+",
    "Peculiar Lighthouse": "C+",
    "Plains": "F",
    "Raucous Carnival": "C+",
    "Razortrap Gorge": "C+",
    "Strangled Cemetery": "C+",
    "Swamp": "F",
    "Thornspire Verge": "C+", 
    "Abandoned Campground": "C+",
    "Forest": "F"
    }

    // return Duskmourn;
    
    let count = 0;

    for (let name in Duskmourn) {
        if (name.includes('//')) {
            count ++;
            console.log(name);
        }
    }
    
    console.log(count);
}
DSK();



