export function DSK() {
    const Duskmourn = {
        
    'Chainsaw': 'B',
    'Fear of Missing Out': 'B',
    'Razor Kin Needle Head': 'C',
    'Roller Crusher Ride': 'A',
    'Screaming Nemesis': 'A-',
    'Cursed Recording': 'D+ (Build Around)',
    'Enduring Courage': 'A-',
    'Red Ley Line': 'F',
    'Walt of Rage': 'A-',
    'Overlord of the Boiler Bages': 'A',
    'Room Char Foyer': 'C+',
    'Silent Hall Creeper': 'A-',
    'Abhorrent Oculus': 'B+',
    'Entity Tracker': 'A-',
    'Mind Skinner': 'F',
    "Tamiyo's Saga": 'D',
    'Enduring Curiosity': 'B+',
    'Lay Line of Transformation': 'F',
    'Overlord of the Flood Pits': 'A-',
    'Marina Vandel Grimor': 'D-',
    'Central Elevator': 'D+',
    'Mirror Room': 'C+',
    'Demonic Counsel': 'D',
    'Come Back Wrong': 'B-',
    'Unstoppable Slasher': 'A',
    'Enduring Tenacity': 'D',
    'Lay Line of the Void': 'Sideboard',
    'Meat Hook Massacre 2': 'C+ (Build Around)',
    'Grievous Wound': 'F',
    'Overlord of the Bale Moor': 'A-',
    'Doomsday Excruciator': 'C- (Build Around)',
    'Unholy Annex': 'B+',
    'Valgo Terror Eater': 'B-',
    'Dazzling Theater//Prop Room': 'D',
    'Ghost Vacuum': 'C',
    'Marvin, Murderous Mimic': 'D+',
    'Dissection Tools': 'A-',
    'Blazemire Verge': 'B',
    "Valgo Gava's Lair": 'B+',
    'Role Model': 'B-',
    'Enduring Innocence': 'B+',
    'Split Up': 'B-',
    'Toby Beasty Befriender': 'B+',
    'Unidentified Hovership': 'A-',
    'Leyline of Hope': 'F',
    'Ghostly Dancers': 'A+',
    'Wandering Rescuers': 'A+',
    'Dazzling Theater': 'F',
    'Overlord of the Mist Moers': 'A+',
    'Dollmaker Shop/Porcelain Gallery': 'A',
    'Razerkin Needlehead': 'C+',
    'Layline of the Rage': 'F',
    'Vault of Rage': 'B+',
    'Overlord of the Boiler Rages': 'A',
    'Charred Foyer': 'C+',
    'Vavo Onslaught': 'A+',
    'Twitching Doll': 'A-',
    'Enduring Vitality': 'B',
    'Hawood Shrier': 'B',
    'Omniverse Flytrap': 'A- (Build Around)',
    'Tyar the Pummeler': 'A',
    'Hedge Shredder': 'A-',
    'Kona Rescue Beast': 'D+',
    'Lon Mutation': 'F',
    'Balustrade Wurm': 'A',
    'Overlord of the Haunt Woods': 'B+',
    'Walk-in Closet': 'D',
    'Soul Warden': 'C',
    'Hallowed Haunting': 'B+ (Build Around)',
    'Phantasmal Image': 'C+',
    'Expropriate': 'D',
    'Cabal Ritual': 'F',
    'Damnation': 'B+',
    'Unholy Heat': 'A-',
    'Maddening Hex': 'F',
    "Naru's Revival": 'F',
    'Collected Company': 'B+ (Build Around)',

    // Gold Uncommons
    "Gremlin Tamer": "B-",
    "Inquisitive Glimmer": "B",
    "Fear of Infinity": "C+",
    "Skull Snap Nuisance": "B-",
    "Disturbing Mirth": "B (Synergy B)",
    "Saw Blade Skin Ripper": "C+",
    "Beastie Beatdown": "B",
    "Wildfire Wicker Folk": "B",
    "Baseball Bat": "C",
    "Shrewd Storyteller": "C",
    "Rise of the Moth": "C+",
    "Shroud Stomper": "C+",
    "Intruding Soul Rager": "C-",
    "Smokey Lounge and Misty Salon": "Build-around C+",
    "Broodspinner": "B+",
    "Drag to the Roots": "C+",
    "Arabella, Abandoned Doll": "B+",
    "Midnight Mayhem": "B",
    "Growing Dread": "B",
    "Oblivious Bookworm": "A-",

    // uncommon artifacts
    "Bear Trap": "D+",
    "Found Footage": "D+",
    "Friendly Teddy": "D+",
    "Glimmerlight": "C",
    "Malevolent Chandelier": "D",
    "Keys to the House": "C",
    "Saw": "D",
    "Attack-in-the-Box": "C-",
    "Haunted Screen": "C",
    "Conductive Machete": "C+",
    "Abandoned Campground (Cycle of Dual Lands)": "C+",
    "Terramorphic Expanse": "B",

    //White commons
    "Jump Scare": "C+",
    "Possessed Goat": "D+",
    "Acrobatic Cheerleader": "C",
    "Surveillance": "C+",
    "Cult Healer": "C-",
    "Hardened Escort": "C",
    "Living Phone": "D",
    "Trapped in the Screen": "B-",
    "Friendly Ghost": "C+",
    "Unsettling Twins": "B",
    "Emerge from the Cocoon": "C+",
    "Fear of Immobility": "C",
    "Room - Grand Entry Way/Elegant Rotunda": "C+",
    "Seize from Slumber": "C",
    "In Spirit": "C",
    "Ethereal Armor": "B-",
    "Optimistic Scavenger": "B+",
    "Shard Mage's Rescue": "B",
    "Unwanted Remake": "F",
    "Veteran Survivor": "C+",
    "Exorcise": "C+",
    "Orphans of the Wheat": "C+",
    "Sheltered by Ghost": "B-",
    "Split Skin Doll": "B",
    "Glimmer Seeker": "C+",
    "Patched Plaything": "B-",
    "Savior of the Small": "C-",
    "Lion Heart Glimmer": "C",
    "Fear of Abduction": "C+",
    "Surgical Suite/Hospital Room": "B",
    "Fear of Surveillance": "C",

    //Blue Commons
    "Enter the Enigma": "C",
    "Unable to Scream": "C-",
    "Creeping Peeper": "D+",
    "Don't Make a Sound": "C-",
    "Piranha Fly": "D+",
    "Stocked Researcher": "C-",
    "Erratic Apparition": "D",
    "Tunnel Surveyor": "C+",
    "Twist Reality": "C+",
    "Clammy Prowler": "D+",
    "Glimmerburst": "B-",
    "Vanish from Sight": "C+",
    "Room - Underwater Tunnel/Slimy Aquarium": "C+",
    "Daggermaw Megalodon": "C+",
    "Room - Meat Locker/Drowned Diner": "C",
    "Scrabbling Skullclaw": "D",
    "Fear of Isolation": "C+",
    "Floodpits Drowner": "B",
    "Get Out": "C+",
    "Paranormal Analyst": "B",
    "Stay Hidden, Stay Silent": "C+",
    "Cursed Windbreaker": "B-",
    "Fear of Impostors": "C+",
    "Unnerving Grasp": "B+",
    "Unwilling Vessel": "C-",
    "Ghostly Keybearer": "D+",
    "Fear of Failed Test": "C-",
    "Fear of Falling": "C",
    "Room - Bottomless Pool/Locker Room": "B-",
    "Duskmourn's Domination": "D+",

    //Black commons
    "Fear of Lost Teeth": "C+",
    "Final Vengeance": "C",
    "Balemurk Leech": "D+",
    "Give In to Violence": "C-",
    "Innocuous Rat": "C+",
    "Winter's Intervention": "C+",
    "Appendage Amalgam": "C-",
    "Cracked Skull": "C",
    "Murder": "C+",
    "Resurrected Cultist": "C+",
    "Cackling Slasher": "D",
    "Fanatic of the Harrowing": "C+/C-",
    "Fear of the Dark": "D",
    "Spectral Snatcher": "C-",
    "Derelict Attic/Widow's Walk": "C-/D+",
    "Valgavoth's Faithful": "C",
    "Cynical Loner": "C",
    "Nowhere to Run": "B-",
    "Osseous Twister": "B",
    "Sporogenic Infection": "B-",
    "Commune with Evil": "C",
    "Killer's Mask": "C",
    "Popular Egotist": "B-",
    "Withering Torment": "C+",
    "Dashing Bloodsucker": "C",
    "Let's Play a Game": "Synergy C",
    "Defiled Crypt/Cadaver Lab": "C",
    "Live or Die": "B-",
    "Miasma Demon": "C-",
    "Vile Mutilator": "C-",

    // Red commons/uncommons
    "clockwork Percussionist": "C+",
    "Turn Inside Out": "C+",
    "Grab the Prizes": "D+",
    "Hand that Feeds": "C-",
    "Ragged Playmate": "C",
    "Scorching Dragonfire": "B",
    "Rampaging Soulrager": "D+",
    "Vicious Clown": "D+",
    "Most Valuable Slayer": "C",
    "Ripchain Razorkin": "C",
    "Boilerbilges Ripper": "D",
    "Impossible Inferno": "C+",
    "Bedhead Beastie": "D+",
    "Glassworks/Shattered Yard": "C+",
    "Ticket Booth/Tunnel of Hate": "C+",
    "Norin, Swift Survivalist": "C+",
    "Trial of Agony": "C+",
    "Violent Urge": "B-",
    "Betrayer's Bargain": "B-",
    "Irreverent Gremlin": "B",
    "Piggy Bank": "B",
    "Pyroclasm": "C+",
    "Untimely Malfunction": "F",
    "Fear of Being Hunted": "C+",
    "Vengeful Possession": "C+",
    "Diversion Specialist": "C",
    "Infernal Phantom": "C",
    "Painter's Studio/Defaced Gallery": "B-",
    "Razorking Horde Caller": "B",
    "Fear of Burning Alive": "B-",

    //Green Commons/uncommons
    "Flesh Burrower": "C",
    "Horrid Vigor": "D+",
    "Manifest Dread": "B",
    "Monstrous Emergence": "C+",
    "Say Its Name": "C+",
    
    "Altanak, the Thrice-Called": "B-",
    "Wary Watchdog": "C+",
    "Cryptid Inspector": "C",
    "Frantic Strength": "C-",
    "Grasping Longneck": "C",
    "Spineseeker Centipede": "C+",
    "Anthropede": "D+",
    "Cautious Survivor": "D+",
    "Bashful Beastie": "C+",
    "Slavering Branchsnapper": "C+",
    "Moldering Gym/Weight Room": "C+",
    "Coordinated Clobbering": "C+",
    "Insidious Fungus": "B-",
    "Patrick Beast": "B-",
    "Cathartic Parting": "D+",
    "House Cartographer": "C+",
    "Overgrown Zealot": "C+",
    "Break Down the Door": "C+",
    "Defiant Survivor": "C+",
    "Fear of Exposure": "C",
    "Under the Skin": "B+",
    "Threats Around Every Corner": "B-",
    "Wickerfolk Thresher": "B-",
    "Rootwise Survivor": "D+",
    "Greenhouse/Rickety Gazebo": "D+",

    //Lands
    "Bleeding Woods": "C",
    "Etched Cornfield": "C",
    "Floodfarm Verge": "C",
    "Gloomlake Verger": "C"

    }

    return Duskmourn;
}

