
export function MH3() {
    const modernHorizons3Ratings = {
        "Abstruse Appropriation": "B+",
        "Accursed Marauder": "C",
        "Aerie Auxiliary": "B",
        "Aether Revolt": "B-",
        "Aether Spike": "C",
        "Ajani Fells the Godsire": "B",
        "Ajani, Nacatl Pariah": "A",
        "Amped Raptor": "A-",
        "Amphibian Downpour": "C",
        "Angel of the Ruins": "C",
        "Annoyed Altisaur": "B",
        "Arcbound Condor": "C+",
        "Argent Dais": "F",
        "Arna Kennerüd, Skycaptain": "B",
        "Ashling, Flame Dancer": "C",
        "Basking Broodscale": "C",
        "Birthing Ritual": "D",
        
        
        "Bloodsoaked Insight": "C+",
        "Brainsurge": "C+",
        "Branching Evolution": "D",
        "Breathe Your Last": "C+",
        "Breya, Etherium Shaper": "D",
        "Bridgeworks Battle": "B",
        "Breaker of Creation": "B",
        
        "Charitable Levy": "F",
        "Chthonian Nightmare": "C",
        "Collective Resistance": "C+",
        "Colossal Dreadmask": "C-",
        "Consign to Memory": "D",
        "Consuming Corruption": "C",
        "Copycrook": "C",
        "Cranial Ram": "C+",
        "Cursed Mirror": "D",
        "Cursed Wombat": "B",
        "Cyclops Superconductor": "C",
        
        
        "Decree of Justice": "C-",
        "Deep Analysis": "C",
        "Detective's Phoenix": "B+",
        "Distinguished Conjurer": "D",
        "Dog Umbra": "C",
        "Dreadmobile": "D+",
        "Dreamdrinker Vampire": "C-",
        "Dreamtide Whale": "D",
        "Drowner of Truth": "B",
        "Drownyard Lurker": "C",
        "Drossclaw": "D",
        "Echoes of Eternity": "D",
        "Electrozoa": "C-",
        "Eladamri, Korvecdal": "C",
        "Eldrazi Linebreaker": "A-",
        "Eldrazi Repurposer": "B-",
        "Emissary of Soulfire": "C+",
        "Emperor of Bones": "A-",
        "Emrakul's Messenger": "B",
        "Envoy of the Ancestors": "C+",
        "Estrid's Invocation": "D",
        "Eviscerator's Insight": "C-",
        "Evolution Witness": "C",
        "Expanding Ooze": "C",
        "Expel the Unworthy": "D+",
        "Fanatic of Rhonas": "B+",
        "Faithful Watchdog": "C",
        "Fanged Flames": "C",
        
        "Flare of Cultivation": "D-",
        "Flare of Duplication": "F",
        "Flare of Fortitude": "D",
        "Flare of Malice": "C+",
        "Fledgling Dragon": "D",
        
        "Fowl Strike": "D",
        "Galvanic Discharge": "B",
        "Genku, Future Shaper": "B+",
        "Gift of the Viper": "D+",
        "Glimpse the Impossible": "C",
        "Glyph Elemental": "B",
        "Golden-Tail Trainer": "C",
        "Gravedig": "D",
        "Grim Servant": "C",
        "Grist, Voracious Larva": "D+",
        "Guardian of the Forgotten": "C",
        "Guide of Souls": "A+",
        "Harbinger of the Seas": "F",
        "Herigast, Erupting Nullkite": "A-",
        "Hexgold Slith": "C",
        "Horrid Shadowspinner": "C",
        "Horrific Assault": "C+",
        "Hope-Ender Coatl": "B-",
        "Hydra Trainer": "D+",
        
        "Imskir Iron-Eater": "D",
        "Infernal Captor": "D+",
        "Indebted Spirit": "C",
        "Inspired Inventor": "C",
        "Inventor's Axe": "C-",
        "Invert Polarity": "B",
        
        "Izzet Generatorium": "C-",
        
        "Kami of Jealous Thirst": "D",
        "Kappa Cannoneer": "B-",
        
        "K'rrik, Son of Yawgmoth": "F",
        "Kozilek's Unsealing": "C",
        "Kudo, King Among Bears": "C-",
        "Laelia, the Blade Reforged": "A",
        
        "Lethal Throwdown": "C",
        "Lion Umbra": "C-",
        
        
        "Malevolent Rumble": "C",
        "Mandibular Kite": "C",
        "Marionette Apprentice": "B+",
        "Marsh Flats": "F",
        "Meteoric Mace": "D",
        "Misty Rainforest": "F",
        "Mogg Mob": "D+",
        "Molten Gatekeeper": "C-",
        "Monstrous Vortex": "D",
        "Muster the Departed": "D",
        "Nadu, Winged Wisdom": "A-",
        "Necrodominance": "D",
        
        "Nightshade Dryad": "C+",
        "Nulldrifter": "B+",
        "Nyxborn Hydra": "C",
        "Nyxborn Unicorn": "C-",
        "Obstinate Gargoyle": "D+",
        "Ocelot Pride": "A",
        "Ondu Knotmaster": "B",
        
        
        "Path of Annihilation": "B+",
        "Party Thrasher": "B",
        "Pearl-Ear Imperial Advisor": "B",
        "Petrifying Meddler": "C",
        "Phlage, Titan of Fire's Fury": "A",
        "Phyrexian Ironworks": "B-",
        "Planar Genesis": "C",
        "Priest of Titania": "D+",
        "Primal Prayers": "D",
        "Prismatic Ending": "A",
        "Propagator Drone": "C+",
        "Psychic Frog": "A-",
        "Proud Pack-Rhino": "C+",
        "Pyretic Rebirth": "C+",
        "Ral and the Implicit Maze": "B",
        "Ral, Monsoon Mage": "C-",
        
        "Reckless Pyrosurfer": "C+",
        "Recruiter of the Guard": "D+",
        "Refurbished Familiar": "C+",
        "Reiterating Bolt": "B",
        "Reef Worm": "C-",
        "Revitalizing Repast": "B-",
        "Riddle Gate Gargoyle": "C+",
        "Ripples of Undeath": "D",
        "Roil Cartographer": "B",
        "Rosheen, Roaring Prophet": "D",
        "Rush of Inspiration": "B-",
        "Sage of the Unknowable": "D",
        
        "Scalding Tarn": "F",
        "Scurrilous Sentry": "C",
        "Scurry of Gremlins": "B+",
        "Sevinne's Reclamation": "C+",
        "Serum Visionary": "C",
        "Shadow of the Second Sun": "C",
        "Shifting Woodland": "B",
        "Shilgengar, Sire of Famine": "A-",
        "Shrieking Drake": "F",
        "Signature Slam": "B",
        
        "Six": "B+",
        "Skittering Precursor": "C",
        "Skoa, Embermage": "C",
        "Smelted Chargebug": "C",
        "Sneaky Snacker": "C+",
        "Solstice Zealot": "C",
        "Solitude": "S",
        "Spawn-Gang Commander": "B+",
        "Springheart Nantuko": "A",
        "Stump Stomp": "B",
        "Suppression Ray": "B",
        
        "Sylvan Safekeeper": "D",
        "Tamiyo, Inquisitive Student": "A",
        "Tamiyo Meets the Story Circle": "D",
        "Temperamental Oozewagg": "C-",
        "Tempest Harvester": "C",
        "Territory Culler": "B",
        "The Creation of Avacyn": "F",
        "The Hunger Tide Rises": "F",
        "Thief of Existence": "C",
        "Thraben Charm": "C",
        "Thriving Skyclaw": "D+",
        "Titans' Vanguard": "B+",
        "Toxic Deluge": "A",
        "Trickster's Elk": "D+",
        "Triton Wavebreaker": "D",
        "Tune the Narrative": "C",
        "Twisted Riddlekeeper": "B",
        "Ugin's Binding": "A",
        "Unfathomable Truths": "C+",
        "Unstable Amulet": "C+",
        "Utter Insignificance": "C",
        "Victimize": "C",
        
        "Voidpouncer": "C-",
        "Volatile Stormdrake": "C+",
        "Voltstorm Angel": "B",
        "Warped Tusker": "C",
        "Warren Soultrader": "C",
        // "Waterlogged Teachings": "C+",
        "Wight of the Reliquary": "B",
        "Wing It": "D",
        "Wither and Bloom": "C+",
        "Wrath of the Skies": "B-",
        "Wumpus Aberration": "B",
        "Wurmcoil Larva": "B-"
    };
    
    return modernHorizons3Ratings;
    
    
}
